import { Sidebar } from "@/components";

export const metadata = {
  title: "Dashboard Page",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <div className="min-w-[280px]">
            <Sidebar />
          </div>
          <main className="w-full">{children}</main>
        </div>
      </body>
    </html>
  );
}
